// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgHnePKMwNjLTgiTvCBE7rvhqGqi9LYM0',
    appId: '1:189380682158:web:866cfb30c4325d0208a83f',
    messagingSenderId: '189380682158',
    projectId: 'dejavu1-c6625',
    authDomain: 'dejavu1-c6625.firebaseapp.com',
    storageBucket: 'dejavu1-c6625.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoHZJ11rWKlSrWpqy5tJMAiVFOObmZBZo',
    appId: '1:189380682158:android:857fb21e3c305bec08a83f',
    messagingSenderId: '189380682158',
    projectId: 'dejavu1-c6625',
    storageBucket: 'dejavu1-c6625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBhJJ6lXybInDdMoly82-o4KySqZx2hk',
    appId: '1:189380682158:ios:167fe3cb407ad68708a83f',
    messagingSenderId: '189380682158',
    projectId: 'dejavu1-c6625',
    storageBucket: 'dejavu1-c6625.appspot.com',
    iosClientId: '189380682158-i445nu16c83haabco1vul1j2brs439r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dejavuClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBhJJ6lXybInDdMoly82-o4KySqZx2hk',
    appId: '1:189380682158:ios:167fe3cb407ad68708a83f',
    messagingSenderId: '189380682158',
    projectId: 'dejavu1-c6625',
    storageBucket: 'dejavu1-c6625.appspot.com',
    iosClientId: '189380682158-i445nu16c83haabco1vul1j2brs439r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dejavuClone',
  );
}
