// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWGJcIQWQ86GxANkx_QvkFJknOnHShPXM',
    appId: '1:766943688283:web:98f86064843e383503b17e',
    messagingSenderId: '766943688283',
    projectId: 'dejavu-65fe7',
    authDomain: 'dejavu-65fe7.firebaseapp.com',
    storageBucket: 'dejavu-65fe7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcPIi0Gi2wGTDmLM4jErHKhifkhIFepF4',
    appId: '1:766943688283:android:2ef2e6fba23bbe2f03b17e',
    messagingSenderId: '766943688283',
    projectId: 'dejavu-65fe7',
    storageBucket: 'dejavu-65fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfUDGKeK6_ZmFR-SMYM6fjsbzWSZkPxdA',
    appId: '1:766943688283:ios:7cc3d65864f5cf0c03b17e',
    messagingSenderId: '766943688283',
    projectId: 'dejavu-65fe7',
    storageBucket: 'dejavu-65fe7.appspot.com',
    iosClientId: '766943688283-fdfohh7inqtcvmff7gufk4tg7crev2m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dejavuClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfUDGKeK6_ZmFR-SMYM6fjsbzWSZkPxdA',
    appId: '1:766943688283:ios:7cc3d65864f5cf0c03b17e',
    messagingSenderId: '766943688283',
    projectId: 'dejavu-65fe7',
    storageBucket: 'dejavu-65fe7.appspot.com',
    iosClientId: '766943688283-fdfohh7inqtcvmff7gufk4tg7crev2m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dejavuClone',
  );
}
